name: trak
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^1.0.0-beta.3


  crypto_font_icons: 0.1.0
  gradient_app_bar: ^0.0.1
  device_simulator: ^0.9.5
  flutter_spinkit: ^4.1.1
  fl_chart: ^0.6.2
  cupertino_icons: ^0.1.2
  http: ^0.12.0+3
  flutter_svg: ^0.15.0
  day: ^0.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf

    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
    - family: Righteous
      fonts:
        - asset: fonts/Righteous-Regular.ttf


  uses-material-design: true



